#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    May 08, 2021 10:52:19 PM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import diet_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    diet_support.set_Tk_var()
    top = Toplevel1 (root)
    diet_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    diet_support.set_Tk_var()
    top = Toplevel1 (w)
    diet_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+380+100")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Diet")
        top.configure(background="#293250")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.033, rely=0.044, relheight=0.9, relwidth=0.925)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#293250")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.31, rely=0.049, height=52, width=211)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#293250")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Select diet period:''')

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.097, rely=0.185, relheight=0.247
                , relwidth=0.362)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Segoe UI} -size 9")
        self.Labelframe1.configure(foreground="white")
        self.Labelframe1.configure(text='''Start Date''')
        self.Labelframe1.configure(background="#293250")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Spinbox1 = tk.Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.055, rely=0.32, relheight=0.25, relwidth=0.219
                , bordermode='ignore')
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="TkDefaultFont")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="blue")
        self.Spinbox1.configure(selectforeground="white")
        self.Spinbox1.configure(textvariable=diet_support.sday)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31',]
        self.Spinbox1.configure(values=self.value_list)

        self.Spinbox1_1 = tk.Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox1_1.place(relx=0.368, rely=0.32, relheight=0.25
                , relwidth=0.219, bordermode='ignore')
        self.Spinbox1_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_1.configure(background="white")
        self.Spinbox1_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_1.configure(font="TkDefaultFont")
        self.Spinbox1_1.configure(foreground="black")
        self.Spinbox1_1.configure(highlightbackground="black")
        self.Spinbox1_1.configure(highlightcolor="black")
        self.Spinbox1_1.configure(insertbackground="black")
        self.Spinbox1_1.configure(selectbackground="blue")
        self.Spinbox1_1.configure(selectforeground="white")
        self.Spinbox1_1.configure(textvariable=diet_support.smonth)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12',]
        self.Spinbox1_1.configure(values=self.value_list)

        self.Spinbox1_2 = tk.Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox1_2.place(relx=0.682, rely=0.32, relheight=0.25
                , relwidth=0.269, bordermode='ignore')
        self.Spinbox1_2.configure(activebackground="#f9f9f9")
        self.Spinbox1_2.configure(background="white")
        self.Spinbox1_2.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_2.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_2.configure(font="TkDefaultFont")
        self.Spinbox1_2.configure(foreground="black")
        self.Spinbox1_2.configure(highlightbackground="black")
        self.Spinbox1_2.configure(highlightcolor="black")
        self.Spinbox1_2.configure(insertbackground="black")
        self.Spinbox1_2.configure(selectbackground="blue")
        self.Spinbox1_2.configure(selectforeground="white")
        self.Spinbox1_2.configure(textvariable=diet_support.syear)
        self.value_list = ['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025','2026','2027','2028','2029','2030','2031','2032','2033','2034','2035','2036','2037','2038','2039','2040','2041','2042','2043','2044','2045','2046','2047','2048','2049','2050','2051','2052','2053','2054','2055','2056','2057','2058','2059','2060','2061','2062','2063','2064','2065','2066','2067','2068','2069','2070','2071','2072','2073','2074','2075','2076','2077','2078','2079','2080','2081','2082','2083','2084','2085','2086','2087','2088','2089','2090','2091','2092','2093','2094','2095','2096','2097','2098','2099',]
        self.Spinbox1_2.configure(values=self.value_list)

        self.Label3_1 = tk.Label(self.Labelframe1)
        self.Label3_1.place(relx=0.368, rely=0.63, height=22, width=36
                , bordermode='ignore')
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#293250")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font="-family {Segoe UI} -size 7")
        self.Label3_1.configure(foreground="#ffffff")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Month''')

        self.Label3_2 = tk.Label(self.Labelframe1)
        self.Label3_2.place(relx=0.682, rely=0.63, height=22, width=36
                , bordermode='ignore')
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#293250")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font="-family {Segoe UI} -size 7")
        self.Label3_2.configure(foreground="#ffffff")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''Year''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.123, rely=0.341, height=22, width=36)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#293250")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 7")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Day''')

        self.Labelframe1_1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_1.place(relx=0.542, rely=0.185, relheight=0.247
                , relwidth=0.362)
        self.Labelframe1_1.configure(relief='groove')
        self.Labelframe1_1.configure(foreground="white")
        self.Labelframe1_1.configure(text='''End Date''')
        self.Labelframe1_1.configure(background="#293250")
        self.Labelframe1_1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_1.configure(highlightcolor="black")

        self.Spinbox1_3 = tk.Spinbox(self.Labelframe1_1, from_=1.0, to=100.0)
        self.Spinbox1_3.place(relx=0.055, rely=0.32, relheight=0.25
                , relwidth=0.219, bordermode='ignore')
        self.Spinbox1_3.configure(activebackground="#f9f9f9")
        self.Spinbox1_3.configure(background="white")
        self.Spinbox1_3.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_3.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_3.configure(font="TkDefaultFont")
        self.Spinbox1_3.configure(foreground="black")
        self.Spinbox1_3.configure(highlightbackground="black")
        self.Spinbox1_3.configure(highlightcolor="black")
        self.Spinbox1_3.configure(insertbackground="black")
        self.Spinbox1_3.configure(selectbackground="blue")
        self.Spinbox1_3.configure(selectforeground="white")
        self.Spinbox1_3.configure(textvariable=diet_support.eday)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31',]
        self.Spinbox1_3.configure(values=self.value_list)

        self.Spinbox1_1_1 = tk.Spinbox(self.Labelframe1_1, from_=1.0, to=100.0)
        self.Spinbox1_1_1.place(relx=0.368, rely=0.32, relheight=0.25
                , relwidth=0.219, bordermode='ignore')
        self.Spinbox1_1_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_1_1.configure(background="white")
        self.Spinbox1_1_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_1_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_1_1.configure(font="TkDefaultFont")
        self.Spinbox1_1_1.configure(foreground="black")
        self.Spinbox1_1_1.configure(highlightbackground="black")
        self.Spinbox1_1_1.configure(highlightcolor="black")
        self.Spinbox1_1_1.configure(insertbackground="black")
        self.Spinbox1_1_1.configure(selectbackground="blue")
        self.Spinbox1_1_1.configure(selectforeground="white")
        self.Spinbox1_1_1.configure(textvariable=diet_support.emonth)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12',]
        self.Spinbox1_1_1.configure(values=self.value_list)

        self.Spinbox1_2_1 = tk.Spinbox(self.Labelframe1_1, from_=1.0, to=100.0)
        self.Spinbox1_2_1.place(relx=0.682, rely=0.32, relheight=0.25
                , relwidth=0.269, bordermode='ignore')
        self.Spinbox1_2_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_2_1.configure(background="white")
        self.Spinbox1_2_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_2_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_2_1.configure(font="TkDefaultFont")
        self.Spinbox1_2_1.configure(foreground="black")
        self.Spinbox1_2_1.configure(highlightbackground="black")
        self.Spinbox1_2_1.configure(highlightcolor="black")
        self.Spinbox1_2_1.configure(insertbackground="black")
        self.Spinbox1_2_1.configure(selectbackground="blue")
        self.Spinbox1_2_1.configure(selectforeground="white")
        self.Spinbox1_2_1.configure(textvariable=diet_support.eyear)
        self.value_list = ['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025','2026','2027','2028','2029','2030','2031','2032','2033','2034','2035','2036','2037','2038','2039','2040','2041','2042','2043','2044','2045','2046','2047','2048','2049','2050','2051','2052','2053','2054','2055','2056','2057','2058','2059','2060','2061','2062','2063','2064','2065','2066','2067','2068','2069','2070','2071','2072','2073','2074','2075','2076','2077','2078','2079','2080','2081','2082','2083','2084','2085','2086','2087','2088','2089','2090','2091','2092','2093','2094','2095','2096','2097','2098','2099',]
        self.Spinbox1_2_1.configure(values=self.value_list)

        self.Label3_1_1 = tk.Label(self.Labelframe1_1)
        self.Label3_1_1.place(relx=0.368, rely=0.63, height=22, width=36
                , bordermode='ignore')
        self.Label3_1_1.configure(activebackground="#f9f9f9")
        self.Label3_1_1.configure(activeforeground="black")
        self.Label3_1_1.configure(background="#293250")
        self.Label3_1_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1_1.configure(font="-family {Segoe UI} -size 7")
        self.Label3_1_1.configure(foreground="#ffffff")
        self.Label3_1_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1_1.configure(highlightcolor="black")
        self.Label3_1_1.configure(text='''Month''')

        self.Label3_2_1 = tk.Label(self.Labelframe1_1)
        self.Label3_2_1.place(relx=0.682, rely=0.63, height=22, width=36
                , bordermode='ignore')
        self.Label3_2_1.configure(activebackground="#f9f9f9")
        self.Label3_2_1.configure(activeforeground="black")
        self.Label3_2_1.configure(background="#293250")
        self.Label3_2_1.configure(disabledforeground="#a3a3a3")
        self.Label3_2_1.configure(font="-family {Segoe UI} -size 7")
        self.Label3_2_1.configure(foreground="#ffffff")
        self.Label3_2_1.configure(highlightbackground="#d9d9d9")
        self.Label3_2_1.configure(highlightcolor="black")
        self.Label3_2_1.configure(text='''Year''')

        self.Label3_3 = tk.Label(self.Labelframe1_1)
        self.Label3_3.place(relx=0.055, rely=0.63, height=22, width=36
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#293250")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font="-family {Segoe UI} -size 7")
        self.Label3_3.configure(foreground="#ffffff")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Day''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.378, rely=0.472, height=34, width=137)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#6dd47e")
        self.Button1.configure(command=diet_support.show)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Button1.configure(foreground="#293250")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Show Dietary''')

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.02, rely=0.027, height=30, width=77)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=diet_support.back)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Button3.configure(foreground="#293250")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''← Back''')

        self.Scrolledlistbox1 = ScrolledListBox(self.Frame1)
        self.Scrolledlistbox1.place(relx=0.022, rely=0.642, relheight=0.333
                , relwidth=0.955)
        self.Scrolledlistbox1.configure(background="#ffd55a")
        self.Scrolledlistbox1.configure(cursor="xterm")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(font="TkFixedFont")
        self.Scrolledlistbox1.configure(foreground="black")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="blue")
        self.Scrolledlistbox1.configure(selectforeground="white")
        self.Scrolledlistbox1.configure(listvariable=diet_support.food)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.022, rely=0.575, height=21, width=530)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#293250")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 9 -weight bold")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''  Item        |  Quantity (oz)  |  Protein (mg)  |   Carbs (mg)  |   Iron (mg)   |   Vit-C (mg)  |   Fat (mg)   ''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.add_command(
                label="NewCommand")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.add_command(
                label="NewCommand")
        Popupmenu1.post(event.x_root, event.y_root)

# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''
    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))
        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')
        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)
        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()
        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, tk.Listbox):
    '''A standard Tkinter Listbox widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)
    def size_(self):
        sz = tk.Listbox.size(self)
        return sz

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





