#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 06, 2021 10:33:23 PM EDT  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import expense_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    expense_support.set_Tk_var()
    top = Toplevel1 (root)
    expense_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    expense_support.set_Tk_var()
    top = Toplevel1 (w)
    expense_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("600x450+380+100")
        top.minsize(120, 1)
        top.maxsize(1370, 749)
        top.resizable(1,  1)
        top.title("Expense")
        top.configure(background="#293250")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.05, rely=0.067, relheight=0.856, relwidth=0.875)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#293250")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.272, rely=0.039, height=61, width=254)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#293250")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Stencil} -size 13")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Generate Expense''')

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.272, rely=0.161, height=61, width=254)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#293250")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Label2.configure(foreground="#ffffff")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Select expense period:''')

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.114, rely=0.338, relheight=0.247
                , relwidth=0.362)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(font="-family {Segoe UI} -size 9")
        self.Labelframe1.configure(foreground="white")
        self.Labelframe1.configure(text='''Start Date''')
        self.Labelframe1.configure(background="#293250")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Spinbox1 = tk.Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox1.place(relx=0.053, rely=0.316, relheight=0.253
                , relwidth=0.221, bordermode='ignore')
        self.Spinbox1.configure(activebackground="#f9f9f9")
        self.Spinbox1.configure(background="white")
        self.Spinbox1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1.configure(font="TkDefaultFont")
        self.Spinbox1.configure(foreground="black")
        self.Spinbox1.configure(highlightbackground="black")
        self.Spinbox1.configure(highlightcolor="black")
        self.Spinbox1.configure(insertbackground="black")
        self.Spinbox1.configure(selectbackground="blue")
        self.Spinbox1.configure(selectforeground="white")
        self.Spinbox1.configure(textvariable=expense_support.sday)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31',]
        self.Spinbox1.configure(values=self.value_list)

        self.Spinbox1_1 = tk.Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox1_1.place(relx=0.368, rely=0.316, relheight=0.253
                , relwidth=0.221, bordermode='ignore')
        self.Spinbox1_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_1.configure(background="white")
        self.Spinbox1_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_1.configure(font="TkDefaultFont")
        self.Spinbox1_1.configure(foreground="black")
        self.Spinbox1_1.configure(highlightbackground="black")
        self.Spinbox1_1.configure(highlightcolor="black")
        self.Spinbox1_1.configure(insertbackground="black")
        self.Spinbox1_1.configure(selectbackground="blue")
        self.Spinbox1_1.configure(selectforeground="white")
        self.Spinbox1_1.configure(textvariable=expense_support.smonth)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12',]
        self.Spinbox1_1.configure(values=self.value_list)

        self.Spinbox1_2 = tk.Spinbox(self.Labelframe1, from_=1.0, to=100.0)
        self.Spinbox1_2.place(relx=0.684, rely=0.316, relheight=0.253
                , relwidth=0.268, bordermode='ignore')
        self.Spinbox1_2.configure(activebackground="#f9f9f9")
        self.Spinbox1_2.configure(background="white")
        self.Spinbox1_2.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_2.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_2.configure(font="TkDefaultFont")
        self.Spinbox1_2.configure(foreground="black")
        self.Spinbox1_2.configure(highlightbackground="black")
        self.Spinbox1_2.configure(highlightcolor="black")
        self.Spinbox1_2.configure(insertbackground="black")
        self.Spinbox1_2.configure(selectbackground="blue")
        self.Spinbox1_2.configure(selectforeground="white")
        self.Spinbox1_2.configure(textvariable=expense_support.syear)
        self.value_list = ['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025','2026','2027','2028','2029','2030','2031','2032','2033','2034','2035','2036','2037','2038','2039','2040','2041','2042','2043','2044','2045','2046','2047','2048','2049','2050','2051','2052','2053','2054','2055','2056','2057','2058','2059','2060','2061','2062','2063','2064','2065','2066','2067','2068','2069','2070','2071','2072','2073','2074','2075','2076','2077','2078','2079','2080','2081','2082','2083','2084','2085','2086','2087','2088','2089','2090','2091','2092','2093','2094','2095','2096','2097','2098','2099',]
        self.Spinbox1_2.configure(values=self.value_list)

        self.Label3_1 = tk.Label(self.Labelframe1)
        self.Label3_1.place(relx=0.368, rely=0.632, height=21, width=34
                , bordermode='ignore')
        self.Label3_1.configure(activebackground="#f9f9f9")
        self.Label3_1.configure(activeforeground="black")
        self.Label3_1.configure(background="#293250")
        self.Label3_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1.configure(font="-family {Segoe UI} -size 7")
        self.Label3_1.configure(foreground="#ffffff")
        self.Label3_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1.configure(highlightcolor="black")
        self.Label3_1.configure(text='''Month''')

        self.Label3_2 = tk.Label(self.Labelframe1)
        self.Label3_2.place(relx=0.684, rely=0.632, height=21, width=34
                , bordermode='ignore')
        self.Label3_2.configure(activebackground="#f9f9f9")
        self.Label3_2.configure(activeforeground="black")
        self.Label3_2.configure(background="#293250")
        self.Label3_2.configure(disabledforeground="#a3a3a3")
        self.Label3_2.configure(font="-family {Segoe UI} -size 7")
        self.Label3_2.configure(foreground="#ffffff")
        self.Label3_2.configure(highlightbackground="#d9d9d9")
        self.Label3_2.configure(highlightcolor="black")
        self.Label3_2.configure(text='''Year''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.133, rely=0.494, height=21, width=34)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#293250")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font="-family {Segoe UI} -size 7")
        self.Label3.configure(foreground="#ffffff")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Day''')

        self.Labelframe1_1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_1.place(relx=0.552, rely=0.338, relheight=0.247
                , relwidth=0.362)
        self.Labelframe1_1.configure(relief='groove')
        self.Labelframe1_1.configure(foreground="white")
        self.Labelframe1_1.configure(text='''End Date''')
        self.Labelframe1_1.configure(background="#293250")
        self.Labelframe1_1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1_1.configure(highlightcolor="black")

        self.Spinbox1_3 = tk.Spinbox(self.Labelframe1_1, from_=1.0, to=100.0)
        self.Spinbox1_3.place(relx=0.053, rely=0.316, relheight=0.253
                , relwidth=0.221, bordermode='ignore')
        self.Spinbox1_3.configure(activebackground="#f9f9f9")
        self.Spinbox1_3.configure(background="white")
        self.Spinbox1_3.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_3.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_3.configure(font="TkDefaultFont")
        self.Spinbox1_3.configure(foreground="black")
        self.Spinbox1_3.configure(highlightbackground="black")
        self.Spinbox1_3.configure(highlightcolor="black")
        self.Spinbox1_3.configure(insertbackground="black")
        self.Spinbox1_3.configure(selectbackground="blue")
        self.Spinbox1_3.configure(selectforeground="white")
        self.Spinbox1_3.configure(textvariable=expense_support.eday)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31',]
        self.Spinbox1_3.configure(values=self.value_list)

        self.Spinbox1_1_1 = tk.Spinbox(self.Labelframe1_1, from_=1.0, to=100.0)
        self.Spinbox1_1_1.place(relx=0.368, rely=0.316, relheight=0.253
                , relwidth=0.221, bordermode='ignore')
        self.Spinbox1_1_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_1_1.configure(background="white")
        self.Spinbox1_1_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_1_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_1_1.configure(font="TkDefaultFont")
        self.Spinbox1_1_1.configure(foreground="black")
        self.Spinbox1_1_1.configure(highlightbackground="black")
        self.Spinbox1_1_1.configure(highlightcolor="black")
        self.Spinbox1_1_1.configure(insertbackground="black")
        self.Spinbox1_1_1.configure(selectbackground="blue")
        self.Spinbox1_1_1.configure(selectforeground="white")
        self.Spinbox1_1_1.configure(textvariable=expense_support.emonth)
        self.value_list = ['01','02','03','04','05','06','07','08','09','10','11','12',]
        self.Spinbox1_1_1.configure(values=self.value_list)

        self.Spinbox1_2_1 = tk.Spinbox(self.Labelframe1_1, from_=1.0, to=100.0)
        self.Spinbox1_2_1.place(relx=0.684, rely=0.316, relheight=0.253
                , relwidth=0.268, bordermode='ignore')
        self.Spinbox1_2_1.configure(activebackground="#f9f9f9")
        self.Spinbox1_2_1.configure(background="white")
        self.Spinbox1_2_1.configure(buttonbackground="#d9d9d9")
        self.Spinbox1_2_1.configure(disabledforeground="#a3a3a3")
        self.Spinbox1_2_1.configure(font="TkDefaultFont")
        self.Spinbox1_2_1.configure(foreground="black")
        self.Spinbox1_2_1.configure(highlightbackground="black")
        self.Spinbox1_2_1.configure(highlightcolor="black")
        self.Spinbox1_2_1.configure(insertbackground="black")
        self.Spinbox1_2_1.configure(selectbackground="blue")
        self.Spinbox1_2_1.configure(selectforeground="white")
        self.Spinbox1_2_1.configure(textvariable=expense_support.eyear)
        self.value_list = ['2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017','2018','2019','2020','2021','2022','2023','2024','2025','2026','2027','2028','2029','2030','2031','2032','2033','2034','2035','2036','2037','2038','2039','2040','2041','2042','2043','2044','2045','2046','2047','2048','2049','2050','2051','2052','2053','2054','2055','2056','2057','2058','2059','2060','2061','2062','2063','2064','2065','2066','2067','2068','2069','2070','2071','2072','2073','2074','2075','2076','2077','2078','2079','2080','2081','2082','2083','2084','2085','2086','2087','2088','2089','2090','2091','2092','2093','2094','2095','2096','2097','2098','2099',]
        self.Spinbox1_2_1.configure(values=self.value_list)

        self.Label3_1_1 = tk.Label(self.Labelframe1_1)
        self.Label3_1_1.place(relx=0.368, rely=0.632, height=21, width=34
                , bordermode='ignore')
        self.Label3_1_1.configure(activebackground="#f9f9f9")
        self.Label3_1_1.configure(activeforeground="black")
        self.Label3_1_1.configure(background="#293250")
        self.Label3_1_1.configure(disabledforeground="#a3a3a3")
        self.Label3_1_1.configure(font="-family {Segoe UI} -size 7")
        self.Label3_1_1.configure(foreground="#ffffff")
        self.Label3_1_1.configure(highlightbackground="#d9d9d9")
        self.Label3_1_1.configure(highlightcolor="black")
        self.Label3_1_1.configure(text='''Month''')

        self.Label3_2_1 = tk.Label(self.Labelframe1_1)
        self.Label3_2_1.place(relx=0.684, rely=0.632, height=21, width=34
                , bordermode='ignore')
        self.Label3_2_1.configure(activebackground="#f9f9f9")
        self.Label3_2_1.configure(activeforeground="black")
        self.Label3_2_1.configure(background="#293250")
        self.Label3_2_1.configure(disabledforeground="#a3a3a3")
        self.Label3_2_1.configure(font="-family {Segoe UI} -size 7")
        self.Label3_2_1.configure(foreground="#ffffff")
        self.Label3_2_1.configure(highlightbackground="#d9d9d9")
        self.Label3_2_1.configure(highlightcolor="black")
        self.Label3_2_1.configure(text='''Year''')

        self.Label3_3 = tk.Label(self.Labelframe1_1)
        self.Label3_3.place(relx=0.053, rely=0.632, height=21, width=34
                , bordermode='ignore')
        self.Label3_3.configure(activebackground="#f9f9f9")
        self.Label3_3.configure(activeforeground="black")
        self.Label3_3.configure(background="#293250")
        self.Label3_3.configure(disabledforeground="#a3a3a3")
        self.Label3_3.configure(font="-family {Segoe UI} -size 7")
        self.Label3_3.configure(foreground="#ffffff")
        self.Label3_3.configure(highlightbackground="#d9d9d9")
        self.Label3_3.configure(highlightcolor="black")
        self.Label3_3.configure(text='''Day''')

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.324, rely=0.649, height=44, width=197)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#6dd47e")
        self.Button1.configure(command=expense_support.show)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Button1.configure(foreground="#293250")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Show Expense''')

        self.Message1 = tk.Message(self.Frame1)
        self.Message1.place(relx=0.171, rely=0.805, relheight=0.164
                , relwidth=0.648)
        self.Message1.configure(background="#ffd55a")
        self.Message1.configure(borderwidth="2")
        self.Message1.configure(font="-family {Segoe UI} -size 10 -weight bold -slant italic")
        self.Message1.configure(foreground="#293250")
        self.Message1.configure(highlightbackground="#d9d9d9")
        self.Message1.configure(highlightcolor="black")
        self.Message1.configure(relief="raised")
        self.Message1.configure(textvariable=expense_support.message)
        self.Message1.configure(width=340)

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.019, rely=0.026, height=30, width=77)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=expense_support.back)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font="-family {Segoe UI} -size 10 -weight bold")
        self.Button3.configure(foreground="#293250")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''← Back''')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.add_command(
                label="NewCommand")
        Popupmenu1.post(event.x_root, event.y_root)

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#ececec")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="#000000")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(foreground="#000000")
        Popupmenu1.add_command(
                label="NewCommand")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





