#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 02, 2021 04:18:29 PM EST  platform: Windows NT

import sys
import os
import expense
import meals
import ypantry
import diet


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def diets():
    diet.create_Toplevel1(root)
    sys.stdout.flush()
      

def expenses():
    expense.create_Toplevel1(root)   
    sys.stdout.flush()

def meal():
    meals.create_Toplevel1(root)
    sys.stdout.flush()

def pantry():
    ypantry.create_Toplevel1(root)
    sys.stdout.flush()


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import kitchen    
    kitchen.vp_start_gui()




