#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Apr 15, 2021 05:13:39 PM EDT  platform: Windows NT

import sys
import recipe_support
import mysql.connector
import json
from datetime import datetime

date = datetime.today().strftime('%d-%b-%Y %H:%M')

nlist = []

def dbmanager():
    global myresult2
    mydb = mysql.connector.connect(host="localhost", user="root", password="pA$$123", database="khelperdb")
    if mydb:
        mycursor = mydb.cursor()
        mycursor.execute("select item from pantry")
        myresult = mycursor.fetchall()
        for i in myresult:
            nlist.append(i[0])

        mycursor2 = mydb.cursor()
        try:
            mycursor2.execute("select ingredients from recipes")
            myresult2 = mycursor2.fetchall()
        except mysql.connector.errors.ProgrammingError:
            mycursor2.execute("select items from pantry")
            myresult2 = mycursor2.fetchall()


try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    dbmanager()
    global needed
    needed = tk.StringVar()
    needed.set(setter(nlist, json.loads(myresult2[recipe_support.index][0])))
    global pantry
    pantry = tk.StringVar()
    pantry.set(nlist)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def back():
    destroy_window()
    sys.stdout.flush()

def generate():
    createText()
    sys.stdout.flush()


def setter(list1, list2):
    global list3
    for i in list1:
        for x in list2:
            if (i in x or i.lower() in x or i in x.lower() or i.lower() in x.lower()):
                list2.remove(x)
    list3 = list2
    return(list2)
    
def createText():
    f = open("Shopping List.txt", "w")
    f.write('__________________________________________\n')
    f.write('______________Kitchen Helper______________\n')
    f.write(date + '\n')
    f.write('\n')
    for i in list3:
        f.write(i + '\n')
    f.close()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import shopping
    shopping.vp_start_gui()




