#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0.1
#  in conjunction with Tcl version 8.6
#    Mar 26, 2021 05:51:18 PM EDT  platform: Windows NT

import sys
import mysql.connector
import os
import addItems

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global plist
    plist = tk.StringVar()
    plist.set(dbmanager())

def dbmanager():
    space1 = '|_______'
    space2 = '_'
    space3 = '__________'
    mydb = mysql.connector.connect(host="localhost", user="root", password="pA$$123", database="khelperdb")
    mycursor = mydb.cursor()

    mycursor.execute("select * from pantry")
    entry = ""
    myresult = mycursor.fetchall()
    for row in myresult:
        entry += (space1 + row[1] + space2 * (15 - len(row[1])) + str(row[2]) + space2 * (17 - len(str(row[2]))) + row[3] + space2 * (10 - len(str(row[3])))+ " ")
    return (entry)

def dbManager2():
    mydb = mysql.connector.connect(host="localhost", user="root", password="pA$$123", database="khelperdb")
    mycursor = mydb.cursor()
    line =(w.Scrolledlistbox1.get('active'))
    lineS = (line.split('|_______',1)[1])
    select =(lineS.split('_')[0])

    sql = "DELETE from pantry WHERE item=" + "'"+ select + "'"
    mycursor.execute(sql)
    mydb.commit()
    
def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def add():
    addItems.create_Toplevel1(root)
    sys.stdout.flush()

def remove():
    dbManager2()
    plist.set(dbmanager())
    sys.stdout.flush()

def back():
    destroy_window()
    

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import ypantry
    ypantry.vp_start_gui()




